sudo: false
dist: trusty
language: node_js
cache: yarn
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - node
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: dist
