# Site settings
title: AlgoRhythms
email: stevenccherry@gmail.com
description: My experiments with the Web Audio API.
baseurl: ""
url: "http://sccherry.github.io/algorhythms"
repo: algorhythms

twitter_username: stevenccherry
github_username:  sccherry
google_analytics: UA-XXXXX-X

safe: true
host: 0.0.0.0
permalink: /posts/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page

# Build settings
markdown: kramdown

exclude: ["README.md", "*.sublime-*"]
