export const SET_MIDI_INPUT = 'SET_MIDI_INPUT';
export const SET_MIDI_INPUT_MAP = 'SET_MIDI_INPUT_MAP';
export const SET_OCTAVE = 'SET_OCTAVE';
export const SET_SOUNDFONT = 'SET_SOUNDFONT';
export const SET_ENVELOPE = 'SET_ENVELOPE';
